include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-webguide
LUCI_TITLE:=LuCI support for Simple Web Guide editor page
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
PKG_VERSION:=1
PKG_RELEASE:=2

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature